export default {
    phones: {
        categoryTitle: "Смартфоны",
        productList: [
            {
                id: 1,
                title: "Oneplus 6T 6GB + 128GB",
                color: "(черный оникс)",
                price: 44500,
                rest: 100,


                type: "смартфон",
                caseType: "классический",
                caseMaterial: "алюминиевый сплав, стекло",
                simType: "nano SIM",
                simCount: 2,
                weight: "180 г",
                size: "160.2x72.9x8.0 мм",
                screenType: "Fluid AMOLED, сенсорный",
                screenSize: "6.55 дюйм",
                screenResolution: "1650 x 720",
                screenRotate: "есть",
                gorillaGlass: "есть",
                mainCamera: "тройная 2/16/48 МП",
                flashType: "тыльная, светодиодная",
                mainCameraFunction: "автофокус, оптическая стабилизация",
                recordingVideo: "есть (MP4)",
                maximumFramerate: "30 кадров/с",
                audioSupport: "MP3, AAC, AAC+, WMA, AMR-NB, AMR-WB, WAV, FLAC, APE, OGG, MID, M4A, IMY, AC3, EAC3, EAC3-JOC, AC4",
                connectionStandart: "GSM 850/900/1800/1900, 3G, 4G LTE, 5G",
                interfaces: "Wi-Fi 802.11ac Dual Band, Bluetooth 5.1, USB 3.1, NFC",
                satellite: "GPS, ГЛОНАСС, BeiDou, Galileo, A-GPS",
                cpu: "Qualcomm Snapdragon 865 (Octa-core, 7nm, up to 2.84 GHz)",
                cpuCoresAmount: "8",
                videoCpu: "Adreno 650",
                memory: "128 Гб",
                ram: "6 Гб",
                acc: "2800 мА⋅ч",
                accType: "Li-Polymer",
                connectorType: "USB Type-C",
                flashLight: "есть",
                supplies: "смартфон, защитная пленка, чехол, кабель Type-C, зарядное устройство Warp Charge 30, шпилька для извлечения SIM",
                announceDate: "2016-04-14",


                imgPath: "main-page/phone-main-page/oneplus_6t_6gb_128gb_black_275_1.png",
                imgAlt: "promo-phone-image",
                discount: true,

                promoBlock: {}
            },
            {
                id: 2,
                title: "Oneplus 6T 8GB + 128GB",
                color: "(синий ультрамарин)",
                price: 61000,
                rest: 60,

                type: "смартфон",
                caseType: "классический",
                caseMaterial: "алюминиевый сплав, стекло",
                simType: "nano SIM",
                simCount: 1,
                weight: "156 г",
                size: "160.2x72.9x8.0 мм",
                screenType: "Fluid AMOLED, сенсорный",
                screenSize: "5.55 дюйм",
                screenResolution: "1950 x 1050",
                screenRotate: "есть",
                gorillaGlass: "есть",
                mainCamera: "тройная 2/16/48 МП",
                flashType: "тыльная, светодиодная",
                mainCameraFunction: "автофокус, оптическая стабилизация",
                recordingVideo: "есть (MP4)",
                maximumFramerate: "30 кадров/с",
                audioSupport: "MP3, AAC, AAC+, WMA, AMR-NB, AMR-WB, WAV, FLAC, APE, OGG, MID, M4A, IMY, AC3, EAC3, EAC3-JOC, AC4",
                connectionStandart: "GSM 850/900/1800/1900, 3G, 4G LTE, 5G",
                interfaces: "Wi-Fi 802.11ac Dual Band, Bluetooth 5.1, USB 3.1, NFC",
                satellite: "GPS, ГЛОНАСС, BeiDou, Galileo, A-GPS",
                cpu: "Qualcomm Snapdragon 865 (Octa-core, 7nm, up to 2.84 GHz)",
                cpuCoresAmount: "8",
                videoCpu: "Adreno 650",
                memory: "128 Гб",
                ram: "8 Гб",
                acc: "3200 мА⋅ч",
                accType: "Li-Polymer",
                connectorType: "USB Type-C",
                flashLight: "есть",
                supplies: "смартфон, защитная пленка, чехол, кабель Type-C, зарядное устройство Warp Charge 30, шпилька для извлечения SIM",
                announceDate: "2017-02-19",

                imgPath: "main-page/phone-main-page/oneplus_6t_8gb_128gb_purple_275_1.png",
                imgAlt: "promo-phone-image",
                discount: false
            },
            {
                id: 3,
                title: "Oneplus 7 Pro 8GB + 256GB",
                color: "(дымчато красный)",
                price: 51000,
                rest: 34,

                type: "смартфон",
                caseType: "классический",
                caseMaterial: "алюминиевый сплав, стекло",
                simType: "nano SIM",
                simCount: 2,
                weight: "156 г",
                size: "160.2x72.9x8.0 мм",
                screenType: "Fluid AMOLED, сенсорный",
                screenSize: "6.25 дюйм",
                screenResolution: "1950 x 1050",
                screenRotate: "есть",
                gorillaGlass: "есть",
                mainCamera: "тройная 2/16/48 МП",
                flashType: "тыльная, светодиодная",
                mainCameraFunction: "автофокус, оптическая стабилизация",
                recordingVideo: "есть (MP4)",
                maximumFramerate: "30 кадров/с",
                audioSupport: "MP3, AAC, AAC+, WMA, AMR-NB, AMR-WB, WAV, FLAC, APE, OGG, MID, M4A, IMY, AC3, EAC3, EAC3-JOC, AC4",
                connectionStandart: "GSM 850/900/1800/1900, 3G, 4G LTE, 5G",
                interfaces: "Wi-Fi 802.11ac Dual Band, Bluetooth 5.1, USB 3.1, NFC",
                satellite: "GPS, ГЛОНАСС, BeiDou, Galileo, A-GPS",
                cpu: "Qualcomm Snapdragon 865 (Octa-core, 7nm, up to 2.84 GHz)",
                cpuCoresAmount: "8",
                videoCpu: "Adreno 850",
                memory: "256 Гб",
                ram: "8 Гб",
                acc: "4100 мА⋅ч",
                accType: "Li-Polymer",
                connectorType: "USB Type-C",
                flashLight: "есть",
                supplies: "смартфон, защитная пленка, чехол, кабель Type-C, зарядное устройство Warp Charge 30, шпилька для извлечения SIM",
                announceDate: "2018-10-02",

                imgPath: "main-page/phone-main-page/oneplus_7_8gb_256gb_red_275_1.png",
                imgAlt: "promo-phone-image",
                discount: true
            },
            {
                id: 4,
                title: "Oneplus 7 Pro 12GB + 256GB",
                color: "(зеркальный серый)",
                price: 76000,
                rest: 32,

                type: "смартфон",
                caseType: "классический",
                caseMaterial: "алюминиевый сплав, стекло",
                simType: "nano SIM",
                simCount: 2,
                weight: "186 г",
                size: "160.2x72.9x8.0 мм",
                screenType: "Fluid AMOLED, сенсорный",
                screenSize: "6.65 дюйм",
                screenResolution: "2950 x 1800",
                screenRotate: "есть",
                gorillaGlass: "есть",
                mainCamera: "тройная 2/16/48 МП",
                flashType: "тыльная, светодиодная",
                mainCameraFunction: "автофокус, оптическая стабилизация",
                recordingVideo: "есть (MP4)",
                maximumFramerate: "30 кадров/с",
                audioSupport: "MP3, AAC, AAC+, WMA, AMR-NB, AMR-WB, WAV, FLAC, APE, OGG, MID, M4A, IMY, AC3, EAC3, EAC3-JOC, AC4",
                connectionStandart: "GSM 850/900/1800/1900, 3G, 4G LTE, 5G",
                interfaces: "Wi-Fi 802.11ac Dual Band, Bluetooth 5.1, USB 3.1, NFC",
                satellite: "GPS, ГЛОНАСС, BeiDou, Galileo, A-GPS",
                cpu: "Qualcomm Snapdragon 865 (Octa-core, 7nm, up to 2.84 GHz)",
                cpuCoresAmount: "8",
                videoCpu: "Adreno 850",
                memory: "256 Гб",
                ram: "12 Гб",
                acc: "4600 мА⋅ч",
                accType: "Li-Polymer",
                connectorType: "USB Type-C",
                flashLight: "есть",
                supplies: "смартфон, защитная пленка, чехол, кабель Type-C, зарядное устройство Warp Charge 30, шпилька для извлечения SIM",
                announceDate: "2020-01-12",


                imgPath: "main-page/phone-main-page/oneplus_7_12gb_256gb_grey_275_1.png",
                imgAlt: "promo-phone-image",
                discount: true
            },

            {
                id: 5,
                title: "Oneplus 6 6GB + 64GB",
                color: "(зеркальный серый)",
                price: 26000,
                rest: 12,

                type: "смартфон",
                caseType: "классический",
                caseMaterial: "алюминиевый сплав, стекло",
                simType: "nano SIM",
                simCount: 1,
                weight: "175 г",
                size: "160.2x72.9x8.0 мм",
                screenType: "Fluid AMOLED, сенсорный",
                screenSize: "4.65 дюйм",
                screenResolution: "1950 x 980",
                screenRotate: "есть",
                gorillaGlass: "есть",
                mainCamera: "тройная 2/16/48 МП",
                flashType: "тыльная, светодиодная",
                mainCameraFunction: "автофокус, оптическая стабилизация",
                recordingVideo: "есть (MP4)",
                maximumFramerate: "30 кадров/с",
                audioSupport: "MP3, AAC, AAC+, WMA, AMR-NB, AMR-WB, WAV, FLAC, APE, OGG, MID, M4A, IMY, AC3, EAC3, EAC3-JOC, AC4",
                connectionStandart: "GSM 850/900/1800/1900, 3G, 4G LTE, 5G",
                interfaces: "Wi-Fi 802.11ac Dual Band, Bluetooth 5.1, USB 3.1, NFC",
                satellite: "GPS, ГЛОНАСС, BeiDou, Galileo, A-GPS",
                cpu: "Qualcomm Snapdragon 865 (Octa-core, 7nm, up to 2.84 GHz)",
                cpuCoresAmount: "8",
                videoCpu: "Adreno 450",
                memory: "64 Гб",
                ram: "6 Гб",
                acc: "3600 мА⋅ч",
                accType: "Li-Polymer",
                connectorType: "USB Type-C",
                flashLight: "есть",
                supplies: "смартфон, защитная пленка, чехол, кабель Type-C, зарядное устройство Warp Charge 30, шпилька для извлечения SIM",
                announceDate: "2014-07-12",


                imgPath: "main-page/phone-main-page/oneplus_7_12gb_256gb_grey_275_1.png",
                imgAlt: "promo-phone-image",
                discount: true
            },


            {
                id: 6,
                title: "Oneplus 6 6GB + 128GB",
                color: "(черный оникс)",
                price: 31000,
                rest: 52,

                type: "смартфон",
                caseType: "классический",
                caseMaterial: "алюминиевый сплав, стекло",
                simType: "nano SIM",
                simCount: 1,
                weight: "196 г",
                size: "160.2x72.9x8.0 мм",
                screenType: "Fluid AMOLED, сенсорный",
                screenSize: "4.25 дюйм",
                screenResolution: "1850 x 1200",
                screenRotate: "есть",
                gorillaGlass: "есть",
                mainCamera: "тройная 2/16/48 МП",
                flashType: "тыльная, светодиодная",
                mainCameraFunction: "автофокус, оптическая стабилизация",
                recordingVideo: "есть (MP4)",
                maximumFramerate: "30 кадров/с",
                audioSupport: "MP3, AAC, AAC+, WMA, AMR-NB, AMR-WB, WAV, FLAC, APE, OGG, MID, M4A, IMY, AC3, EAC3, EAC3-JOC, AC4",
                connectionStandart: "GSM 850/900/1800/1900, 3G, 4G LTE, 5G",
                interfaces: "Wi-Fi 802.11ac Dual Band, Bluetooth 5.1, USB 3.1, NFC",
                satellite: "GPS, ГЛОНАСС, BeiDou, Galileo, A-GPS",
                cpu: "Qualcomm Snapdragon 865 (Octa-core, 7nm, up to 2.84 GHz)",
                cpuCoresAmount: "8",
                videoCpu: "Adreno 850",
                memory: "128 Гб",
                ram: "6 Гб",
                acc: "3760 мА⋅ч",
                accType: "Li-Polymer",
                connectorType: "USB Type-C",
                flashLight: "есть",
                supplies: "смартфон, защитная пленка, чехол, кабель Type-C, зарядное устройство Warp Charge 30, шпилька для извлечения SIM",
                announceDate: "2015-11-12",


                imgPath: "main-page/phone-main-page/oneplus_7_12gb_256gb_grey_275_1.png",
                imgAlt: "promo-phone-image",
                discount: true
            },
        ],
    },

    accessoires: {
        categoryTitle: "Аксессуары",
        productList: [
            {
                id: 11,
                title: "Беспроводные наушники OnePlus Bullets Wireless",
                price: 12000,
                rest: 12,
                imgPath: "main-page/accessoires-main-page/oneplus_bullets_wireless_275_1.png",
                imgAlt: "promo-accessoires-image",
                discount: false
            },
            {
                id: 21,
                title: "Адаптер OnePlus Dash Power",
                price: 6000,
                rest: 42,
                imgPath: "main-page/accessoires-main-page/oneplus_dash_charger_275_1.png",
                imgAlt: "promo-accessoires-image",
                discount: false
            },
            {
                id: 34,
                title: "Автомобильное зарядное устройство OnePlus Warp Charge",
                price: 9800,
                rest: 17,
                imgPath: "main-page/accessoires-main-page/oneplus_warp_charge_30_275_1.png",
                imgAlt: "promo-accessoires-image",
                discount: true
            },
            {
                id: 151,
                title: "Адаптер OnePlus Type-C - 3.5мм",
                price: 2000,
                rest: 52,
                imgPath: "main-page/accessoires-main-page/oth_cable_oneplus_type_c_275_1.png",
                imgAlt: "promo-accessoires-image",
                discount: false
            }
        ],
    },

    gadgets: {
        categoryTitle: "Гаджеты",
        productList: [
            {
                id: 566,
                title: "Зубная электрощетка Soocas X3 Sonic Electric ToothBrush",
                price: 7900,
                rest: 32,
                imgPath: "main-page/gadgets-main-page/electric_tooth_brush_275_1.png",
                imgAlt: "promo-gadgets-image",
                discount: false
            },
            {
                id: 766,
                title: "Робот-пылесос Roborock Sweep One",
                price: 17200,
                rest: 52,
                imgPath: "main-page/gadgets-main-page/roborock_sweep_one_275_1.png",
                imgAlt: "promo-gadgets-image",
                discount: true
            },
            {
                id: 567,
                title: "Автомобильное зарядное устройство ZMI Car Charger AP821",
                price: 11500,
                rest: 78,
                imgPath: "main-page/gadgets-main-page/digital_display_car_charger_275_1.png",
                imgAlt: "promo-gadgets-image",
                discount: false
            },
            {
                id: 311,
                title: "Зеркало для макияжа Amiro Lux High Color",
                price: 15000,
                rest: 7,
                imgPath: "main-page/gadgets-main-page/amiro_lux_high_color_275_1.png",
                imgAlt: "promo-gadgets-image",
                discount: false
            },
        ],
    },


    slider: {},
};
